ALTER USER HR ACCOUNT UNLOCK; ---HR KULLANICISININ KILIDINI ACMA

ALTER USER HR IDENTIFIED BY HR; --HR KULLANICISINA SIFRE BELIRLEME

SELECT*FROM ALL_TABLES WHERE OWNER='HR'; --HR KULLANICISININ TABLE'LARINI GORUNTULEME

SELECT*FROM REGIONS;
SELECT*FROM COUNTRIES;


SELECT C.COUNTRY_NAME ,C.COUNTRY_ID,R.REGION_NAME
FROM COUNTRIES C
JOIN REGIONS R ON C.REGION_ID=R.REGION_ID;

SELECT*FROM LOCATIONS;


SELECT L.*,
C.COUNTRY_NAME ,C.COUNTRY_ID,R.REGION_NAME
FROM COUNTRIES C
JOIN REGIONS R ON C.REGION_ID=R.REGION_ID
FULL JOIN LOCATIONS L ON L.COUNTRY_ID=C.COUNTRY_ID ;

