UNDEFINE repository_name

CREATE USER &&repository_name IDENTIFIED BY &&repository_name 
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp;

GRANT CONNECT, 
      RESOURCE, 
      CREATE VIEW, 
      CREATE PUBLIC SYNONYM 
TO &&repository_name WITH ADMIN OPTION;

GRANT ALTER ANY ROLE, 
      ALTER ANY SEQUENCE, 
      ALTER ANY TABLE, 
      ALTER TABLESPACE,
      ALTER ANY TRIGGER, 
      COMMENT ANY TABLE, 
      CREATE ANY SEQUENCE, 
      CREATE ANY TABLE,
      CREATE ANY TRIGGER, 
      CREATE ROLE, 
      CREATE TABLESPACE, 
      CREATE USER, 
      DROP ANY SEQUENCE, 
      DROP ANY TABLE, 
      DROP ANY TRIGGER, 
      DROP TABLESPACE, 
      DROP USER, 
      DROP ANY ROLE, 
      GRANT ANY ROLE, 
      INSERT ANY TABLE, 
      SELECT ANY TABLE, 
      UPDATE ANY TABLE 
TO &&repository_name; 