SELECT*FROM EMPLOYEES;

SELECT*FROM EMPLOYEES
WHERE EMPLOYEE_ID=100;
-----------------------------------------

SELECT*FROM EMPLOYEES
WHERE EMPLOYEE_ID !=100;

SELECT*FROM EMPLOYEES
WHERE NOT EMPLOYEE_ID=100;

SELECT*FROM EMPLOYEES
WHERE EMPLOYEE_ID <> 100;

SELECT*FROM EMPLOYEES
WHERE EMPLOYEE_ID ^=100;

----------------------------------------------------
SELECT COUNTRY_ID FROM COUNTRIES;  --25 ROWS

SELECT DISTINCT COUNTRY_ID FROM LOCATIONS; --14 ROWS

SELECT COUNTRY_ID FROM COUNTRIES
MINUS
SELECT COUNTRY_ID FROM LOCATIONS;  -- 25-14=11 ROWS   (A/B)
----------------------------------------------------------------------
SELECT COUNTRY_ID FROM COUNTRIES
INTERSECT
SELECT COUNTRY_ID FROM LOCATIONS;  --14ROWS    (AnB)       


SELECT COUNTRY_ID FROM LOCATIONS 
INTERSECT
SELECT COUNTRY_ID FROM COUNTRIES;  --14ROWS    (AnB)

---------------------------------------------------------------------

