
SELECT *FROM EMPLOYEES;
SELECT*FROM DEPARTMENTS;

SELECT*FROM
EMPLOYEES E
JOIN DEPARTMENTS D ON
D.DEPARTMENT_ID=E.DEPARTMENT_ID;
------------LEFT JOIN--------------------------------
SELECT*FROM
EMPLOYEES E
LEFT JOIN DEPARTMENTS D ON
D.DEPARTMENT_ID=E.DEPARTMENT_ID;

SELECT*FROM
EMPLOYEES E
LEFT OUTER JOIN DEPARTMENTS D ON
D.DEPARTMENT_ID=E.DEPARTMENT_ID;

SELECT*FROM
EMPLOYEES E,DEPARTMENTS D
WHERE E.DEPARTMENT_ID=D.DEPARTMENT_ID(+);

-----------------------------------------
SELECT*FROM
EMPLOYEES E
LEFT JOIN DEPARTMENTS D ON
D.DEPARTMENT_ID=E.DEPARTMENT_ID
WHERE D.DEPARTMENT_ID IS  NULL; 



SELECT*FROM
EMPLOYEES E
LEFT JOIN DEPARTMENTS D ON
D.DEPARTMENT_ID=E.DEPARTMENT_ID
WHERE D.DEPARTMENT_ID IS NOT NULL 
MINUS
SELECT*FROM
EMPLOYEES E
JOIN DEPARTMENTS D ON
D.DEPARTMENT_ID=E.DEPARTMENT_ID;

-----------RIGHT JOIN--------------------------------
SELECT*FROM
EMPLOYEES E
RIGHT JOIN DEPARTMENTS D ON
D.DEPARTMENT_ID=E.DEPARTMENT_ID;

SELECT*FROM
EMPLOYEES E
RIGHT OUTER JOIN DEPARTMENTS D ON
D.DEPARTMENT_ID=E.DEPARTMENT_ID;

SELECT*FROM 
EMPLOYEES E,DEPARTMENTS D
WHERE E.DEPARTMENT_ID(+)=D.DEPARTMENT_ID;

-----------------------------------------------------------
SELECT*FROM
EMPLOYEES E
RIGHT JOIN DEPARTMENTS D ON
D.DEPARTMENT_ID=E.DEPARTMENT_ID
WHERE E.DEPARTMENT_ID IS  NULL ;


SELECT*FROM
EMPLOYEES E
RIGHT JOIN DEPARTMENTS D ON
D.DEPARTMENT_ID=E.DEPARTMENT_ID
WHERE E.DEPARTMENT_ID IS NOT  NULL
MINUS
SELECT*FROM
EMPLOYEES E
JOIN DEPARTMENTS D ON
D.DEPARTMENT_ID=E.DEPARTMENT_ID;