ALTER USER HR ACCOUNT UNLOCK; ---HR KULLANICISININ KILIDINI ACMA

ALTER USER HR IDENTIFIED BY HR; --HR KULLANICISINA SIFRE BELIRLEME

SELECT*FROM ALL_TABLES WHERE OWNER='HR'; --HR KULLANICISININ TABLE'LARINI GORUNTULEME

SELECT*FROM REGIONS;
SELECT*FROM COUNTRIES;


SELECT c.country_name,c.country_ýd,r.regýon_name
FROM COUNTRIES C
JOIN REGIONS R ON C.REGION_ID=R.REGION_ID

SELECT*FROM LOCATIONS;


SELECT L.*,
c.country_name,c.country_ýd,r.regýon_name
FROM COUNTRIES C
JOIN REGIONS R ON c.regýon_ýd=r.regýon_ýd
FULL JOIN LOCATIONS L ON l.country_ýd=c.country_ýd;

