
--------CALCULATED COLUMN / ALIAS-----------

SELECT*FROM EMPLOYEES;

SELECT 
FIRST_NAME,LAST_NAME,SALARY
FROM EMPLOYEES;

SELECT 
FIRST_NAME AS ADI,
LAST_NAME AS SOYADI,
SALARY AS MAAS
FROM EMPLOYEES;

SELECT 
FIRST_NAME  ADI,
LAST_NAME  SOYADI,
SALARY  MAAS
FROM EMPLOYEES;

SELECT 
FIRST_NAME  "ADI",
LAST_NAME  "SOYADI",
SALARY*12  "YILLIK MAAS"
FROM EMPLOYEES;

SELECT
CONCAT(CONCAT(FIRST_NAME,' '),LAST_NAME) FULL_NAME,
SALARY*12 AS ANNUAL_SALARY
FROM EMPLOYEES;

SELECT
FIRST_NAME||' '||LAST_NAME "AD-SOYAD",
SALARY*12 "YILLIK MAAS"
FROM EMPLOYEES;

