SELECT JOB_ID FROM JOBS
UNION 
SELECT JOB_ID FROM JOB_HISTORY;

SELECT JOB_ID FROM JOBS
UNION ALL
SELECT JOB_ID FROM JOB_HISTORY;

SELECT*FROM EMPLOYEES
ORDER BY SALARY;
---------------------------------------------------

SELECT*FROM EMPLOYEES
WHERE SALARY BETWEEN 3000 AND 4000
ORDER BY SALARY;


SELECT*FROM EMPLOYEES
WHERE SALARY >=3000 AND SALARY<=4000
ORDER BY SALARY;


SELECT*FROM EMPLOYEES
WHERE SALARY BETWEEN 3000 AND 4000
MINUS
SELECT*FROM EMPLOYEES
WHERE SALARY >=3000 AND SALARY<=4000;

--FETCH FIRST 3 ROWS ONLY/WHERE ROWNUM<=3
-------------------------------------------


SELECT*FROM EMPLOYEES
ORDER BY SALARY DESC;

SELECT 
    ROWNUM AS RANK,
    LAST_NAME,SALARY
FROM
    (SELECT 
    LAST_NAME,SALARY FROM EMPLOYEES
    ORDER BY SALARY DESC)
WHERE ROWNUM<=3;

SELECT 
LAST_NAME,SALARY
FROM EMPLOYEES
ORDER BY SALARY DESC
FETCH FIRST 3 ROWS ONLY;

SELECT 
LAST_NAME,SALARY
FROM EMPLOYEES
WHERE ROWNUM<=3
ORDER BY SALARY DESC;

--------------------------------------------

SELECT*FROM EMPLOYEES
ORDER BY HIRE_DATE;

SELECT
    ROWNUM AS SENIOR,
    E.LAST_NAME,E.HIRE_DATE
FROM
    (SELECT 
    LAST_NAME,HIRE_DATE FROM EMPLOYEES
    ORDER BY HIRE_DATE) E
WHERE ROWNUM<=4;

---------------------------------------------

SELECT SALARY,COUNT(*)FROM EMPLOYEES
WHERE SALARY BETWEEN 3000 AND 4000
GROUP BY SALARY
ORDER BY SALARY;

