SELECT*FROM EMPLOYEES
ORDER BY DEPARTMENT_ID,SALARY DESC;


---HER DEPARTMANDA KAC PERSONEL VAR

SELECT DEPARTMENT_ID,COUNT(*) AS NUM_OF_PERSONAL
FROM EMPLOYEES            
GROUP BY DEPARTMENT_ID
ORDER BY DEPARTMENT_ID;


---DEPARTMANA GORE EN FAZLA MAAS ALAN PERSONELI BULMA

SELECT 
E.DEPARTMENT_ID,MAX(E.SALARY),
COUNT(*) AS NUM_OF_PERSONAL
FROM EMPLOYEES E                                      
GROUP BY E.DEPARTMENT_ID
ORDER BY E.DEPARTMENT_ID;



SELECT 
(
    SELECT CONCAT(CONCAT(FIRST_NAME,' '),LAST_NAME) 
    FROM EMPLOYEES WHERE DEPARTMENT_ID=E.DEPARTMENT_ID 
    ORDER BY SALARY DESC FETCH FIRST 1 ROW ONLY
) AS FULL_NAME,
E.DEPARTMENT_ID,
MAX(E.SALARY)AS MAX_SALARY
FROM EMPLOYEES E                                      
GROUP BY E.DEPARTMENT_ID
ORDER BY E.DEPARTMENT_ID;




SELECT * FROM
(
    SELECT * FROM
    (
        SELECT 
        (
            SELECT CONCAT(CONCAT(FIRST_NAME,' '),LAST_NAME) 
            FROM EMPLOYEES WHERE DEPARTMENT_ID=E.DEPARTMENT_ID 
            ORDER BY SALARY DESC FETCH FIRST 1 ROW ONLY
        )  
        AS FULL_NAME,
        E.DEPARTMENT_ID,
        MAX(E.SALARY)AS MAX_SALARY
        FROM EMPLOYEES E 
        WHERE E.DEPARTMENT_ID IS NOT NULL 
        GROUP BY E.DEPARTMENT_ID
        ORDER BY E.DEPARTMENT_ID
    )
    UNION
    SELECT*FROM
    (
        SELECT 
        CONCAT(CONCAT(FIRST_NAME,' '),LAST_NAME),
        DEPARTMENT_ID,
        SALARY AS MAX_SALARY
        FROM EMPLOYEES  
        WHERE DEPARTMENT_ID IS NULL
        ORDER BY SALARY DESC FETCH FIRST 1 ROW ONLY 
    )
)
ORDER BY DEPARTMENT_ID;



SELECT 
FIRST_NAME,LAST_NAME,SALARY 
FROM EMPLOYEES  
WHERE DEPARTMENT_ID IS NULL 
ORDER BY SALARY DESC;

SELECT 
FIRST_NAME,LAST_NAME,SALARY 
FROM EMPLOYEES 
WHERE DEPARTMENT_ID=50 
ORDER BY SALARY DESC 
fetch first 1 row only;







