SELECT* FROM EMPLOYEES;

SELECT FIRST_NAME,LAST_NAME FROM EMPLOYEES;

--------CHARACTER FUNCTIONS
--------CONCAT  (IKI METINI BIRLESTIRME)

SELECT                                                 
CONCAT(CONCAT(FIRST_NAME,' '),LAST_NAME)AS FULL_NAME   
FROM EMPLOYEES;


SELECT FIRST_NAME,LAST_NAME,
CONCAT(CONCAT(FIRST_NAME,' '),LAST_NAME)AS FULL_NAME   
FROM EMPLOYEES;

SELECT 
CONCAT(CONCAT(last_name, '''s job category is '), job_id) 
FROM EMPLOYEES;
-----------------------------------
--------CONVERSION FUNCTIONS
--------NVL(NULL,...)    NULL IFADE .... OLSUN
-------TO CHAR(...)      INT IFADEYI CHAR A DONUSTURMEK

SELECT* FROM EMPLOYEES;

SELECT
FIRST_NAME,LAST_NAME,
MANAGER_ID FROM EMPLOYEES;

SELECT 
FIRST_NAME,LAST_NAME,
NVL(TO_CHAR(MANAGER_ID), 'BIG BOSS')
FROM EMPLOYEES;

--------------------------------------
-----DATE/TIME FUNCTIONS
-----KIM KAÇ GUN-AY-YIL CALISTI
SELECT
FIRST_NAME,LAST_NAME,
HIRE_DATE
FROM EMPLOYEES;

SELECT FIRST_NAME,LAST_NAME,HIRE_DATE,
ROUND(SYSDATE-HIRE_DATE) AS DAYS_WORKED
FROM EMPLOYEES;


SELECT FIRST_NAME,LAST_NAME,HIRE_DATE,
ROUND(MONTHS_BETWEEN(SYSDATE, HIRE_DATE)) AS MONTHS_WORKED
FROM EMPLOYEES;

SELECT FIRST_NAME,LAST_NAME,HIRE_DATE,
ROUND(MONTHS_BETWEEN(SYSDATE, HIRE_DATE)/12) AS YEARS_WORKED
FROM EMPLOYEES ORDER BY 4 DESC;

SELECT FIRST_NAME,LAST_NAME,HIRE_DATE,
ROUND(SYSDATE-HIRE_DATE)AS DAYS_WORKED,
ROUND(MONTHS_BETWEEN(SYSDATE,HIRE_DATE))AS MONTHS_WORKED,
ROUND(MONTHS_BETWEEN(SYSDATE,HIRE_DATE)/12) AS YEARS_WORKED
FROM EMPLOYEES;
-------------------------------

SELECT FIRST_NAME,LAST_NAME,HIRE_DATE,
TO_CHAR(HIRE_DATE, 'DY, DD-MON-YYYY') AS FORMAT1, 
to_char(HIRE_DATE,'Month DDth, YYYY') AS FORMAT2
FROM EMPLOYEES;

