


---DEPARTMANA GORE EN FAZLA MAAS ALAN PERSONELI BULMA

SELECT EMP.*FROM(
SELECT * FROM
(
    SELECT * FROM
    (
        SELECT 
        (
            SELECT CONCAT(CONCAT(FIRST_NAME,' '),LAST_NAME) 
            FROM EMPLOYEES WHERE DEPARTMENT_ID=E.DEPARTMENT_ID 
            ORDER BY SALARY DESC FETCH FIRST 1 ROW ONLY
        )  
        AS FULL_NAME,
        E.DEPARTMENT_ID,
        MAX(E.SALARY)AS MAX_SALARY
        FROM EMPLOYEES E 
        WHERE E.DEPARTMENT_ID IS NOT NULL 
        GROUP BY E.DEPARTMENT_ID
        ORDER BY E.DEPARTMENT_ID
    )
    UNION
    SELECT*FROM
    (
        SELECT 
        CONCAT(CONCAT(FIRST_NAME,' '),LAST_NAME),
        DEPARTMENT_ID,
        SALARY AS MAX_SALARY
        FROM EMPLOYEES  
        WHERE DEPARTMENT_ID IS NULL
        ORDER BY SALARY DESC FETCH FIRST 1 ROW ONLY 
    )
)
ORDER BY DEPARTMENT_ID) E 
JOIN EMPLOYEES EMP ON
E.FULL_NAME=CONCAT(CONCAT(EMP.FIRST_NAME,' '),EMP.LAST_NAME)









