SELECT 
EMPLOYEE_ID,FIRST_NAME,LAST_NAME,JOB_ID,MANAGER_ID,DEPARTMENT_ID,LEVEL 
FROM EMPLOYEES
CONNECT BY PRIOR EMPLOYEE_ID = MANAGER_ID
START WITH MANAGER_ID IS NULL ORDER BY LEVEL;

SELECT 
EMPLOYEE_ID,FIRST_NAME,LAST_NAME,JOB_ID,MANAGER_ID,DEPARTMENT_ID,
(SELECT FIRST_NAME FROM EMPLOYEES E WHERE E.EMPLOYEE_ID = EMP.MANAGER_ID)AS BOSS
FROM 
EMPLOYEES EMP  ORDER BY 1;

SELECT 
EMPLOYEE_ID,FIRST_NAME,LAST_NAME,JOB_ID,MANAGER_ID,DEPARTMENT_ID,LEVEL ,
(SELECT FIRST_NAME FROM EMPLOYEES E WHERE E.EMPLOYEE_ID = EMP.MANAGER_ID)AS BOSS
FROM EMPLOYEES EMP
CONNECT BY PRIOR EMPLOYEE_ID = MANAGER_ID
START WITH MANAGER_ID IS NULL ORDER BY LEVEL;



SELECT 
EMPLOYEE_ID,FIRST_NAME,LAST_NAME,JOB_ID,MANAGER_ID,DEPARTMENT_ID,LEVEL ,
SYS_CONNECT_BY_PATH(FIRST_NAME,'/') AS HIER
FROM EMPLOYEES
CONNECT BY PRIOR EMPLOYEE_ID = MANAGER_ID
START WITH MANAGER_ID IS NULL ORDER BY LEVEL;


