
--------AGGREGATE FUNCTIONS--------------

SELECT*FROM EMPLOYEES
ORDER BY COMMISSION_PCT;


SELECT COMMISSION_PCT,
COUNT(*)
FROM EMPLOYEES
GROUP BY COMMISSION_PCT
ORDER BY COMMISSION_PCT;

-----------------COUNT(*)--------------------

SELECT COUNT(*)
FROM EMPLOYEES;
--107 ROWS  (NUMBER OF ROWS)


---------COUNT([ALL | DISTINCT] expr)------------

SELECT
COUNT(DISTINCT COMMISSION_PCT)
FROM EMPLOYEES;
--7 ROWS (NUMBER OF DIFFERENT VALUES)(NOT INCLUDING NULL)


SELECT 
COUNT( ALL COMMISSION_PCT)
FROM EMPLOYEES;
--35 ROWS (NOT INCLUDING NULL)


SELECT 
COUNT(COMMISSION_PCT)
FROM EMPLOYEES;    
--35 ROWS (NOT INCLUDING NULL)  SAME =(COUNT(ALL...)


