--EQUI JOIN--

SELECT*FROM EMPLOYEES;
SELECT*FROM DEPARTMENTS;

SELECT 
DEPARTMENT_ID,COUNT(*)
FROM DEPARTMENTS
GROUP BY DEPARTMENT_ID;

SELECT
*
FROM EMPLOYEES E,DEPARTMENTS D
WHERE E.DEPARTMENT_ID=D.DEPARTMENT_ID
ORDER BY E.DEPARTMENT_ID;

SELECT *
FROM   employees e
       NATURAL JOIN departments d;

SELECT D.MANAGER_ID,D.DEPARTMENT_ID,D.DEPARTMENT_NAME,D.LOCATION_ID,
(SELECT EMP.FIRST_NAME||' '||EMP.LAST_NAME FROM EMPLOYEES EMP WHERE EMP.EMPLOYEE_ID=D.MANAGER_ID  ) AS MANAGER
FROM DEPARTMENTS D
WHERE D.MANAGER_ID IS NOT NULL;


SELECT
EMPLOYEE_ID,FIRST_NAME,LAST_NAME,EMAIL,
PHONE_NUMBER,HIRE_DATE,JOB_ID,
SALARY,COMMISSION_PCT,E.DEPARTMENT_ID,
DEPARTMENT_NAME,LOCATION_ID
FROM EMPLOYEES E,DEPARTMENTS D
WHERE E.DEPARTMENT_ID=D.DEPARTMENT_ID
AND DEPARTMENT_NAME='IT';

SELECT 
    DEPARTMENT_NAME,
    (
    SELECT EMP.FIRST_NAME||' '||EMP.LAST_NAME FROM EMPLOYEES EMP 
    WHERE EMP.EMPLOYEE_ID=D.MANAGER_ID
    )AS MANAGER,
    EMPLOYEE_ID,JOB_ID,
    E.FIRST_NAME||' '||E.LAST_NAME AS STAFF 
FROM EMPLOYEES E,DEPARTMENTS D
WHERE E.DEPARTMENT_ID=D.DEPARTMENT_ID
ORDER BY D.DEPARTMENT_ID;







