
--single-row subquery
SELECT*FROM EMPLOYEES
WHERE JOB_ID=(SELECT JOB_ID FROM EMPLOYEES WHERE LAST_NAME='Gates');


SELECT 
MONTHS_BETWEEN('31-12-2021','31-12-2020')
FROM DUAL;

SELECT ROUND(MONTHS_BETWEEN(SYSDATE,HIRE_DATE)) AS AY,
FIRST_NAME,LAST_NAME,HIRE_DATE,JOB_ID,DEPARTMENT_ID FROM EMPLOYEES
ORDER BY 1 DESC;


SELECT*FROM JOB_HISTORY;
SELECT*FROM EMPLOYEES;
SELECT*FROM DEPARTMENTS;

--NVL(value, default)
SELECT 
EMPLOYEE_ID, FIRST_NAME, LAST_NAME,JOB_ID, SALARY,MANAGER_ID,
NVL(TO_CHAR(DEPARTMENT_ID),'NO DEPARTMENT') AS  DEPARTMENT_ID,
NVL(TO_CHAR(COMMISSION_PCT),'NO COMMISSION')
FROM EMPLOYEES
ORDER BY 4;

SELECT
DEPARTMENT_ID,DEPARTMENT_NAME,LOCATION_ID,
NVL(MANAGER_ID,0)AS MANAGER_ID
FROM DEPARTMENTS;


SELECT
DEPARTMENT_ID,DEPARTMENT_NAME,LOCATION_ID,MANAGER_ID,
NVL2(MANAGER_ID,'MANAGER ON','MANAGER OFF' )AS MANAGER
FROM DEPARTMENTS;

--------------------------------------------------------------
--NULLIF(expr1,expr2)



SELECT NULLIF(5,2) FROM DUAL;---5
SELECT NULLIF(5,5) FROM DUAL;--null


SELECT E.EMPLOYEE_ID,E.FIRST_NAME,E.LAST_NAME,
E.HIRE_DATE,
J.START_DATE,J.END_DATE,
E.JOB_ID,
J.JOB_ID AS JOB_HISTORY,
NULLIF(E.JOB_ID,J.JOB_ID),
E.DEPARTMENT_ID,
J.DEPARTMENT_ID AS DEPARTMENT_HISTORY,
NULLIF(E.DEPARTMENT_ID,J.DEPARTMENT_ID)
FROM EMPLOYEES E
JOIN JOB_HISTORY J ON 
J.EMPLOYEE_ID=E.EMPLOYEE_ID;


