SELECT*FROM REGIONS;


---CREATING A COPY OF TABLE----------------

CREATE TABLE REGIONS2 AS SELECT*FROM REGIONS; 
-------------------------------------------

SELECT*FROM REGIONS2;

SELECT*FROM EMPLOYEES 
WHERE SALARY>&MAAS   ---ENTER VALUE FOR (MAAS)(INPUT)
ORDER BY SALARY DESC;  

SELECT*FROM REGIONS 
WHERE REGION_ID=&ID_GIR; ---ENTER VALUE FOR (ID_DIR)(INPUT)

SELECT*FROM EMPLOYEES;

SET WRAP OFF; --SQLPLUS RUN SCRIPT SONUCU DUZENLEME

SELECT*FROM EMPLOYEES;

SET HEAD OFF; --SQLPLUS RUN SCRIPT BASLIK SILME

SELECT*FROM EMPLOYEES;

---------------------------------






