SELECT 
EMPLOYEE_ID,FIRST_NAME,LAST_NAME,JOB_ID,MANAGER_ID,DEPARTMENT_ID,LEVEL 
FROM EMPLOYEES
CONNECT BY PRIOR EMPLOYEE_ID = MANAGER_ID
START WITH MANAGER_ID IS NULL ORDER BY LEVEL;

SELECT 
EMPLOYEE_ID,FIRST_NAME,LAST_NAME,JOB_ID,MANAGER_ID,DEPARTMENT_ID
,(select FIRST_NAME from EMPLOYEES e where e.EMPLOYEE_ID = emp.MANAGER_ID)as boss
FROM 
EMPLOYEES emp  ORDER BY 1;

SELECT 
EMPLOYEE_ID,FIRST_NAME,LAST_NAME,JOB_ID,MANAGER_ID,DEPARTMENT_ID,LEVEL ,
(select FIRST_NAME from EMPLOYEES e where e.EMPLOYEE_ID = emp.MANAGER_ID)as boss
FROM EMPLOYEES emp
CONNECT BY PRIOR EMPLOYEE_ID = MANAGER_ID
START WITH MANAGER_ID IS NULL ORDER BY LEVEL;



SELECT 
EMPLOYEE_ID,FIRST_NAME,LAST_NAME,JOB_ID,MANAGER_ID,DEPARTMENT_ID,LEVEL ,
SYS_CONNECT_BY_PATH(FIRST_NAME,'/') AS HiER
FROM EMPLOYEES
CONNECT BY PRIOR EMPLOYEE_ID = MANAGER_ID
START WITH MANAGER_ID IS NULL ORDER BY LEVEL;


