SELECT * FROM CATEGORIES;

CREATE TABLE NAMES
(
NAME VARCHAR2 (20)
);

SELECT *FROM NAMES;

INSERT ALL
INTO NAMES VALUES ('ALÝ')
INTO NAMES VALUES ('MEHMET')
INTO NAMES VALUES ('AYÞE')
INTO NAMES VALUES ('EMÝNE')
INTO NAMES VALUES ('HAKAN')
INTO NAMES VALUES ('YILMAZ')
SELECT * FROM DUAL;



SELECT
NAME,
NVL(LAG(NAME)OVER(ORDER BY NAME),(SELECT NAME FROM
(SELECT NAME,ROWNUM FROM NAMES ORDER BY ROWNUM DESC)
WHERE ROWNUM=1)) AS ROWNUMBER
FROM NAMES;

SELECT ROWNUM FROM NAMES ORDER BY ROWNUM;

SELECT 
NAME,ROWNUM AS ASCENDING
FROM 
NAMES
ORDER BY ROWNUM;

SELECT *
FROM (SELECT ROWNUM FROM NAMES ORDER BY ROWNUM DESC)
WHERE ROWNUM=1;

SELECT NAME FROM
(SELECT NAME,ROWNUM FROM NAMES ORDER BY ROWNUM DESC)
WHERE ROWNUM=1;


SELECT Level AS ASCENDING
FROM Dual
CONNECT BY Level <= 6;
