select * from user_sys_privs order by privilege; --KULLANICI YETKILERI OGRENME

SELECT USERNAME,ACCOUNT_STATUS FROM DBA_USERS ORDER BY 2 DESC; --KULLANICILARI VE DURUMLARINI OGRENME

ALTER USER HR ACCOUNT UNLOCK; ---HR KULLANICISININ KILIDINI ACMA

ALTER USER HR IDENTIFIED BY HR; --HR KULLANICISINA SIFRE BELIRLEME

SELECT*FROM ALL_TABLES WHERE OWNER='HR'; --HR KULLANICISININ TABLE'LARINI GORUNTULEME

SELECT OWNER,COUNT(*) FROM ALL_TABLES GROUP BY OWNER; --HANGI KULLANICININ KAC TABLE'I VAR

SELECT table_name, column_name, data_type, data_length FROM ALL_TAB_COLUMNS ; --TABLE'LARDAKI KOLON BILGISI

SELECT * FROM ALL_TAB_COLUMNS WHERE OWNER <> 'SYS' AND OWNER <> 'SYSTEM' ;
SELECT * FROM ALL_TAB_COLUMNS WHERE OWNER NOT IN('SYS','SYSTEM');

SELECT * FROM ALL_TAB_COLUMNS WHERE OWNER ='HR' ORDER BY TABLE_NAME ;
--------------------------------------------------------

CREATE USER username IDENTIFIED BY yourpassword;

CREATE USER username IDENTIFIED BY yourpassword
DEFAULT TABLESPACE SYSTEM TEMPORARY TABLESPACE TEMP 
QUOTA UNLIMITED ON SYSTEM;

DROP USER username;

ALTER USER username ACCOUNT UNLOCK;
ALTER USER username ACCOUNT LOCK;

GRANT 
CONNECT, RESOURCE, DBA,
CREATE SESSION , ---OTURUM ACMA YETKISI
CREATE TABLE,
CREATE SEQUENCE, --SEQUENCE OLUSTURMA
CREATE VIEW,
CREATE PROCEDURE
TO username;





