SELECT*FROM DBA_USERS;

SELECT *FROM DBA_ROLES;

SELECT*FROM DBA_TABLESPACES;

SELECT *FROM DBA_TABLES;

SELECT *FROM DBA_ROLLBACK_SEGS;

SELECT*FROM DBA_CONSTRAINTS;

SELECT*FROM DBA_DATA_FILES;

SELECT 
TABLESPACE_NAME,BYTES
FROM DBA_DATA_FILES;

SELECT*FROM DBA_FREE_SPACE;

SELECT 
TABLESPACE_NAME,SUM(BYTES)
FROM DBA_FREE_SPACE
GROUP BY TABLESPACE_NAME;

SELECT 
DFS.TABLESPACE_NAME,
DBF.BYTES,SUM(DFS.BYTES) AS FREE_SPACE
FROM DBA_DATA_FILES DBF
JOIN DBA_FREE_SPACE DFS
ON DBF.TABLESPACE_NAME=DFS.TABLESPACE_NAME
GROUP BY DFS.TABLESPACE_NAME,DBF.BYTES;


SELECT*FROM DBA_SEGMENTS;

SELECT 
SEGMENT_TYPE,COUNT(*)
FROM DBA_SEGMENTS
GROUP BY SEGMENT_TYPE
ORDER BY COUNT(*) DESC;


SELECT OWNER,
SEGMENT_NAME,SUM(BYTES)
FROM DBA_SEGMENTS
WHERE SEGMENT_TYPE='TABLE'
GROUP BY OWNER,SEGMENT_NAME
ORDER BY 1,2;


SELECT 
SEGMENT_NAME,SUM(BYTES)
FROM USER_SEGMENTS
WHERE SEGMENT_TYPE='TABLE'
GROUP BY SEGMENT_NAME
ORDER BY 1,2;


SELECT
SEGMENT_TYPE,COUNT(*)
FROM DBA_SEGMENTS
GROUP BY SEGMENT_TYPE;

SELECT
OWNER,COUNT(*)
FROM DBA_SEGMENTS
GROUP BY OWNER;


SELECT*FROM DBA_EXTENTS;

SELECT*FROM DBA_INDEXES;

SELECT 
OWNER,COUNT(*)
FROM DBA_INDEXES
GROUP BY OWNER;

SELECT*FROM DBA_OBJECTS;

SELECT 
OWNER,COUNT(*)
FROM DBA_OBJECTS
GROUP BY OWNER;

SELECT * FROM DBA_ROLE_PRIVS;

SELECT*FROM DBA_SEQUENCES;

SELECT*FROM DBA_SYNONYMS;

SELECT*FROM DBA_VIEWS;

SELECT
OWNER,COUNT(*)
FROM DBA_VIEWS
GROUP BY OWNER;


SELECT *FROM DBA_TAB_PRIVS;

SELECT GRANTOR,COUNT(*)
FROM DBA_TAB_PRIVS
GROUP BY GRANTOR;

SELECT GRANTEE,COUNT(*)
FROM DBA_TAB_PRIVS
GROUP BY GRANTEE;

SELECT OWNER,COUNT(*)
FROM DBA_TAB_PRIVS
GROUP BY OWNER;

SELECT *
FROM DBA_TAB_PRIVS
WHERE GRANTOR='HR' OR OWNER='HR' OR GRANTEE='HR';





