DROP TABLE TEST2 CASCADE CONSTRAINTS;


ALTER TABLE EMPLOYEES DISABLE ALL TRIGGERS;

ALTER TRIGGER secure_employees DISABLE;

ALTER TRIGGER secure_employees ENABLE;

ALTER TRIGGER secure_employees COMPILE;



CREATE TABLE TEST1
(
ID NUMBER,
NAME VARCHAR2(20),
SURNAME VARCHAR2(20)
);


COMMENT ON COLUMN TEST1.ID IS 'TABLONUN NUMARASI'; 
COMMENT ON COLUMN TEST1.NAME IS 'ISIM'; 
COMMENT ON COLUMN TEST1.SURNAME IS 'SOYISIM';
COMMENT ON TABLE TEST1 IS 'BU BÝR TEST TABLOSUDUR';

INSERT INTO TEST1 (ID,NAME,SURNAME) VALUES (1,'ALI','ALP');
INSERT INTO TEST1 (ID,NAME,SURNAME) VALUES (2,'VELI','KAYA');
INSERT INTO TEST1 (ID,NAME,SURNAME) VALUES (3,'HALE','CAN');
INSERT INTO TEST1 (ID,NAME,SURNAME) VALUES (4,'LALE','YILMAZ');
INSERT INTO TEST1 (ID,NAME,SURNAME) VALUES (5,'JALE','DEMIR');

SELECT *FROM TEST1;

SELECT *FROM TEST1 
WHERE NAME LIKE '%E';

UPDATE TEST1 SET SURNAME='SAHIN' WHERE ID=2;

UPDATE TEST1 SET SURNAME='CELIK' WHERE SURNAME='CAN';

UPDATE TEST1 SET SURNAME='YILDIZ' WHERE SURNAME='ALP';

SELECT *FROM TEST1;

ALTER TABLE TEST1 ADD AGE NUMBER;
COMMENT ON COLUMN TEST1.AGE IS 'YAS';

UPDATE TEST1 SET AGE=30;

UPDATE TEST1 SET AGE=20 WHERE ID=1;
UPDATE TEST1 SET AGE=25 WHERE ID=2;
UPDATE TEST1 SET AGE=35 WHERE ID=4;
UPDATE TEST1 SET AGE=40 WHERE ID=5;

ALTER TABLE TEST1 ADD GENDER VARCHAR2(1);
COMMENT ON COLUMN TEST1.GENDER IS 'CINSIYET';

UPDATE TEST1 SET GENDER='E' WHERE ID=1;
UPDATE TEST1 SET GENDER='E' WHERE ID=2;
UPDATE TEST1 SET GENDER='K' WHERE ID=3;
UPDATE TEST1 SET GENDER='K' WHERE ID=4;
UPDATE TEST1 SET GENDER='K' WHERE ID=5;

SELECT *FROM TEST1
WHERE NAME LIKE '%E' AND AGE>=35;

SELECT NAME AS ISIM,SURNAME AS SOYISIM
FROM TEST1
WHERE AGE<30;

SELECT*FROM TEST1 
WHERE GENDER='K';
