SELECT*FROM ALL_TABLES;

SELECT USERNAME,ACCOUNT_STATUS FROM DBA_USERS ORDER BY 2 DESC;

SELECT * FROM DBA_USERS ORDER BY 4 DESC;


--------HANGI KULLANICININ KAC TABLE'I VAR (NULL DEGERLER ILE)--------

SELECT U.USERNAME,U.ACCOUNT_STATUS,
COUNT(AT.TABLE_NAME)
FROM DBA_USERS U
FULL JOIN ALL_TABLES AT ON
AT.OWNER=U.USERNAME
GROUP BY U.USERNAME,U.ACCOUNT_STATUS
ORDER BY 2 DESC;

-------------------------------------------------

SELECT OWNER,COUNT(*) FROM ALL_TABLES GROUP BY OWNER ORDER BY 2 DESC;

SELECT*FROM ALL_TABLES WHERE OWNER='ORDSYS';

SELECT*FROM ORDSYS.SI_IMAGE_FORMATS_TAB;


SELECT COUNT(*)FROM ALL_TABLES;---2160
SELECT COUNT(*)FROM ALL_ALL_TABLES; ---2200

----------------------------------------------------

SELECT* FROM ALL_TAB_COLUMNS WHERE OWNER='HR' ;

------------------------------------------------------
---KENDI TABLE'LARINI GORUNTULEME

SELECT *FROM USER_TABLES; 

SELECT * FROM TABS;  --(VIEW)

SELECT*FROM ALL_TABLES WHERE OWNER='.....';

-------------------------------------------------
(SELECT *FROM USER_TABLES)
MINUS                 --(NO DIFFERENCE)
(SELECT * FROM TABS);

------------------------------------------------
---KENDI INDEX'LERINI GORUNTULEME

SELECT*FROM USER_INDEXES;

SELECT*FROM IND;   --(VIEW)

------------------------------------------------
(SELECT *FROM USER_INDEXES)
MINUS                 --(NO DIFFERENCE)
(SELECT * FROM IND);

---------------------------------------------------
---KENDI SEQUENCE'LERINI GORUNTULEME (SIRA,DIZI)

SELECT*FROM USER_SEQUENCES;

SELECT*FROM SEQ;   --(VIEW)

------------------------------------------------
(SELECT *FROM USER_SEQUENCES)
MINUS                 --(NO DIFFERENCE)
(SELECT * FROM SEQ);

---------------------------------------------------
-------KENDI VIEW'LERINI GORUNTULEME

SELECT*FROM USER_VIEWS;

-------------------------------------------------
---KENDI SYNONYM'LERINI GORUNTULEME(ES ANLAMLAR)

SELECT*FROM USER_SYNONYMS;

SELECT*FROM SYN;   --(VIEW)

------------------------------------------------
(SELECT *FROM USER_SYNONYMS)
MINUS                 --(NO DIFFERENCE)
(SELECT * FROM SYN);

----------------------------------------
-------KENDI SEKMENT'LERINI GORUNTULEME (PARCALAR)

SELECT*FROM USER_SEGMENTS;

-------------------------------------------------
-------KENDI EXTENT'LERINI GORUNTULEME (KAPSAMLAR-GENISLEME)

SELECT*FROM USER_EXTENTS;

-------------------------------------------------

SELECT*FROM USER_USERS;

SELECT*FROM ALL_USERS;
----------------------------------------
-------KENDI CONSTRAINT'LARINI GORUNTULEME (TABLOLARDAKI KISITLAMALAR)

SELECT*FROM USER_CONSTRAINTS;

SELECT*FROM USER_CONS_COLUMNS; --KISITLAMALAR HANGI TABLO VE  HANGI SATIR UZERINDE


SELECT
    C.TABLE_NAME,C.CONSTRAINT_NAME,C.R_CONSTRAINT_NAME,
    A.COLUMN_NAME,B.TABLE_NAME,B.COLUMN_NAME 
FROM
    USER_CONSTRAINTS C,
    USER_CONS_COLUMNS A,
    USER_CONS_COLUMNS B
WHERE
    C.CONSTRAINT_NAME=A.CONSTRAINT_NAME(+)
AND C.R_CONSTRAINT_NAME=B.CONSTRAINT_NAME(+);

------------------------------------------------
-------KENDI TUM OBJELERINI GORUNTULEME 

SELECT *FROM USER_OBJECTS;

SELECT 
OBJECT_NAME,OBJECT_TYPE
FROM USER_OBJECTS
ORDER BY OBJECT_TYPE;

SELECT 
OBJECT_TYPE,COUNT(*)
FROM USER_OBJECTS
GROUP BY OBJECT_TYPE
ORDER BY COUNT(*) DESC;

-----------------------------------------------
SELECT*FROM USER_ROLE_PRIVS;
SELECT*FROM  USER_SYS_PRIVS order by PRIVILEGE;

SELECT*FROM USER_TAB_PRIVS;  ---SAHIP OLDUGU HAK ALDIGI VE HAK VERDIGI NESNE HAKLARI

-------------------------------------------------







